---

spine-1:
  managementip: 198.51.100.254/24
  managementgw: 198.51.100.1
  site: ny
  role: spine
  interfaces:
    - number: 1
      ip: 172.16.0.1/30
      description: P2P Link to Leaf-1
    - number: 2
      ip: 172.16.0.5/30
      description: P2P Link to Leaf-2
  loopbacks:
    - number: 0
      ip: 192.168.0.1/32
  routerid: 192.168.0.1
  bgpnetworks:
    - 192.168.0.1/32
  peergroups:
    - name: EBGP-TO-LEAF
      maxroutes: 12000
      remoteas: 65100
      neighbors:
        - 172.16.0.2
        - 172.16.0.6  
spine-2:
  managementip: 198.51.100.253/24
  managementgw: 198.51.100.1
  site: ny
  role: spine
  interfaces:
    - number: 1
      ip: 172.16.0.9/30
      description: P2P Link to Leaf-1
    - number: 2
      ip: 172.16.0.13/30
      description: P2P Link to Leaf-2
  loopbacks:
    - number: 0
      ip: 192.168.0.2/32
  routerid: 192.168.0.2
  bgpnetworks:
    - 192.168.0.2/32
  peergroups:
    - name: EBGP-TO-LEAF
      maxroutes: 12000
      remoteas: 65100
      neighbors:
       - 172.16.0.10
       - 172.16.0.14
leaf-1:
  managementip: 198.51.100.252/24
  managementgw: 198.51.100.1
  site: ny
  role: leaf
leaf-2:
  managementip: 198.51.100.251/24
  managementgw: 198.51.100.1
  site: ny
  role: leaf
